{
 "title": "AI Workload Stats",
 "tags": [ "AI Workload" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU Cores (Cluster)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(workload:cpu_usage_cores:sum[$__range])"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time((avg(DCGM_FI_DEV_GPU_UTIL >= 0))[$__range:]) / 100"
    }
   ]
  },
  {
   "title": "Number of Kubeflow User Profiles",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (namespace) (max_over_time(kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'}[$__range])))"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Utilization by Profile Namespace",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  max by (uid, namespace) (\n        kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on (namespace) group_right() \n           max_over_time(kube_pod_status_phase{phase='Running'}[$__range]) > 0\n      )\n  )\n ",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", image!=\"\"}[5m])) * on(namespace) group_left() kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'}"
    },
    {
     "expr": "(sum by (namespace) (max_over_time(container_memory_working_set_bytes{container!=\"\", image!=\"\", namespace!~\"openshift-.*\"}[$__range]) )) * on(namespace) \n  kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'}"
    },
    {
     "expr": "count by (namespace) (\n   kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on(namespace) group_right()\n    label_replace(\n      label_replace(max_over_time(DCGM_FI_DEV_GPU_UTIL[$__range]) >= 0, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"),\n      \"pod\", \n      \"$1\", \n      \"exported_pod\", \n      \"(.*)\"\n    )\n)"
    },
    {
     "expr": "avg_over_time(\n (\n  avg by (namespace) (\n     kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on(namespace) group_right()\n      label_replace(\n        label_replace(DCGM_FI_DEV_GPU_UTIL >= 0, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"),\n        \"pod\", \n        \"$1\", \n        \"exported_pod\", \n        \"(.*)\"\n      )\n   ) / 100\n  )[$__range:]\n)"
    },
    {
     "expr": "sum by (namespace) (\n   kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on(namespace) group_right()\n    label_replace(\n      label_replace(sum_over_time(DCGM_FI_DEV_POWER_USAGE[$__range]) >= 0, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"),\n      \"pod\", \n      \"$1\", \n      \"exported_pod\", \n      \"(.*)\"\n    )\n)"
    }
   ]
  },
  {
   "title": "GPU Utilization by Model and Profile Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count by (namespace, modelName) (\n   kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on(namespace) group_right()\n    label_replace(\n      label_replace(max_over_time(DCGM_FI_DEV_GPU_UTIL[$__range]) >= 0, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"),\n      \"pod\", \n      \"$1\", \n      \"exported_pod\", \n      \"(.*)\"\n    )\n)"
    },
    {
     "expr": "avg_over_time(\n  (avg by (namespace, modelName) (\n    kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on(namespace) group_right()\n     label_replace(\n          DCGM_FI_DEV_GPU_UTIL{exported_namespace!~''} >= 0,\n          \"namespace\",\n          \"$1\",\n          \"exported_namespace\", \n          \"(.*)\"\n      \n    )    \n   ) / 100)[$__range:]\n  )"
    },
    {
     "expr": "sum by (namespace, modelName) (\n   kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on(namespace) group_right()\n    label_replace(\n      label_replace(sum_over_time(DCGM_FI_DEV_POWER_USAGE[$__range]) >= 0, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"),\n      \"pod\", \n      \"$1\", \n      \"exported_pod\", \n      \"(.*)\"\n    )\n)"
    }
   ]
  },
  {
   "title": "CPU Utilization by Profile Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", image!=\"\"}[5m])) * on(namespace) group_left() kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Active pods by Profile Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (\n  max by (uid, namespace) (\n        kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on (namespace) group_right() \n          kube_pod_status_phase{phase='Running'} > 0\n      )\n  )\n ",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage by Model and Profile Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, modelName) (\n   kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on(namespace) group_right()\n    label_replace(\n      label_replace(DCGM_FI_DEV_POWER_USAGE >= 0, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"),\n      \"pod\", \n      \"$1\", \n      \"exported_pod\", \n      \"(.*)\"\n    )\n)",
     "legendFormat": "{{namespace}} / {{ modelName}}"
    }
   ]
  },
  {
   "title": "GPU Utilization by Model and Profile Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (namespace, modelName) (\n  kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on(namespace) group_right()\n   label_replace(\n        DCGM_FI_DEV_GPU_UTIL{exported_namespace!~''} >= 0,\n        \"namespace\",\n        \"$1\",\n        \"exported_namespace\", \n        \"(.*)\"\n )    \n) / 100 ",
     "legendFormat": "{{namespace}} / {{modelName}}"
    }
   ]
  },
  {
   "title": "GPU Allocations by Model and Profile Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace, modelName) (\n   kube_namespace_labels{label_app_kubernetes_io_part_of='kubeflow-profile'} * on(namespace) group_right()\n    label_replace(\n      label_replace(DCGM_FI_DEV_GPU_UTIL >= 0, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"),\n      \"pod\", \n      \"$1\", \n      \"exported_pod\", \n      \"(.*)\"\n    )\n)",
     "legendFormat": "{{namespace}} / {{modelName}}"
    }
   ]
  }
 ]
}