{
 "title": "Pod NVIDIA GPU Stats",
 "tags": [ "AI Workload" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},  namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "POD GPU Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (exported_pod, exported_container, modelName, UUID) (max_over_time((DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"} >= 0)[$__range:])) / 100\n\n"
    },
    {
     "expr": "avg by (exported_pod, exported_container, modelName, UUID) (avg_over_time((DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"} >= 0)[$__range:])) / 100"
    },
    {
     "expr": "max by (exported_pod, exported_container, modelName, UUID) (max_over_time(DCGM_FI_DEV_FB_USED{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"}[$__range:]) >= 0) * 1024 * 1024"
    },
    {
     "expr": "avg by (exported_pod, exported_container, modelName, UUID) (avg_over_time(DCGM_FI_DEV_FB_USED{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"}[$__range:]) >= 0) * 1024 * 1024"
    }
   ]
  },
  {
   "title": "GPU Memory Usage (Average by Pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_namespace, exported_pod) (DCGM_FI_DEV_FB_USED{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"}) * 1024 * 1024",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "GPU Utilization (Average by Pod)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_pod, exported_namespace) (DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"} / 100 >= 0)",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  }
 ]
}