apiVersion: v1
data:
  pod-nvidia-gpu-stats.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 3,
      "iteration": 1710280835618,
      "links": [],
      "panels": [
        {
          "columns": [],
          "fontSize": "100%",
          "gridPos": {
            "h": 9,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "hideTimeOverride": false,
          "id": 4,
          "interval": "",
          "links": [],
          "pageSize": null,
          "scroll": true,
          "showHeader": true,
          "sort": {
            "col": null,
            "desc": false
          },
          "styles": [
            {
              "alias": "Time",
              "dateFormat": "YYYY-MM-DD HH:mm:ss",
              "pattern": "Time",
              "type": "hidden"
            },
            {
              "alias": "Container",
              "colorMode": null,
              "colors": [
                "rgba(245, 54, 54, 0.9)",
                "rgba(237, 129, 40, 0.89)",
                "rgba(50, 172, 45, 0.97)"
              ],
              "dateFormat": "YYYY-MM-DD HH:mm:ss",
              "decimals": 2,
              "mappingType": 1,
              "pattern": "exported_container",
              "thresholds": [],
              "type": "string",
              "unit": "short"
            },
            {
              "alias": "Pod",
              "colorMode": null,
              "colors": [
                "rgba(245, 54, 54, 0.9)",
                "rgba(237, 129, 40, 0.89)",
                "rgba(50, 172, 45, 0.97)"
              ],
              "dateFormat": "YYYY-MM-DD HH:mm:ss",
              "decimals": 2,
              "mappingType": 1,
              "pattern": "exported_pod",
              "thresholds": [],
              "type": "string",
              "unit": "short"
            },
            {
              "alias": "model",
              "colorMode": null,
              "colors": [
                "rgba(245, 54, 54, 0.9)",
                "rgba(237, 129, 40, 0.89)",
                "rgba(50, 172, 45, 0.97)"
              ],
              "dateFormat": "YYYY-MM-DD HH:mm:ss",
              "decimals": 2,
              "mappingType": 1,
              "pattern": "modelName",
              "thresholds": [],
              "type": "number",
              "unit": "short"
            },
            {
              "alias": "Max Utilization",
              "colorMode": null,
              "colors": [
                "rgba(245, 54, 54, 0.9)",
                "rgba(237, 129, 40, 0.89)",
                "rgba(50, 172, 45, 0.97)"
              ],
              "dateFormat": "YYYY-MM-DD HH:mm:ss",
              "decimals": 3,
              "mappingType": 1,
              "pattern": "Value #A",
              "thresholds": [],
              "type": "number",
              "unit": "short"
            },
            {
              "alias": "GPU ID",
              "colorMode": null,
              "colors": [
                "rgba(245, 54, 54, 0.9)",
                "rgba(237, 129, 40, 0.89)",
                "rgba(50, 172, 45, 0.97)"
              ],
              "dateFormat": "YYYY-MM-DD HH:mm:ss",
              "decimals": 2,
              "mappingType": 1,
              "pattern": "UUID",
              "thresholds": [],
              "type": "string",
              "unit": "short"
            },
            {
              "alias": "Max Memory",
              "colorMode": null,
              "colors": [
                "rgba(245, 54, 54, 0.9)",
                "rgba(237, 129, 40, 0.89)",
                "rgba(50, 172, 45, 0.97)"
              ],
              "dateFormat": "YYYY-MM-DD HH:mm:ss",
              "decimals": 2,
              "mappingType": 1,
              "pattern": "Value #B",
              "thresholds": [],
              "type": "number",
              "unit": "bytes"
            },
            {
              "alias": "Avg Utilization",
              "colorMode": null,
              "colors": [
                "rgba(245, 54, 54, 0.9)",
                "rgba(237, 129, 40, 0.89)",
                "rgba(50, 172, 45, 0.97)"
              ],
              "dateFormat": "YYYY-MM-DD HH:mm:ss",
              "decimals": 3,
              "mappingType": 1,
              "pattern": "Value #C",
              "thresholds": [],
              "type": "number",
              "unit": "short"
            },
            {
              "alias": "Avg Memory",
              "colorMode": null,
              "colors": [
                "rgba(245, 54, 54, 0.9)",
                "rgba(237, 129, 40, 0.89)",
                "rgba(50, 172, 45, 0.97)"
              ],
              "dateFormat": "YYYY-MM-DD HH:mm:ss",
              "decimals": 2,
              "mappingType": 1,
              "pattern": "Value #D",
              "thresholds": [],
              "type": "number",
              "unit": "bytes"
            }
          ],
          "targets": [
            {
              "expr": "max by (exported_pod, exported_container, modelName, UUID) (max_over_time((DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"} >= 0)[$__range:])) / 100\n\n",
              "format": "table",
              "instant": true,
              "intervalFactor": 1,
              "refId": "A"
            },
            {
              "expr": "avg by (exported_pod, exported_container, modelName, UUID) (avg_over_time((DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"} >= 0)[$__range:])) / 100",
              "format": "table",
              "instant": true,
              "intervalFactor": 1,
              "refId": "C"
            },
            {
              "expr": "max by (exported_pod, exported_container, modelName, UUID) (max_over_time(DCGM_FI_DEV_FB_USED{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"}[$__range:]) >= 0) * 1024 * 1024",
              "format": "table",
              "instant": true,
              "intervalFactor": 1,
              "refId": "B"
            },
            {
              "expr": "avg by (exported_pod, exported_container, modelName, UUID) (avg_over_time(DCGM_FI_DEV_FB_USED{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"}[$__range:]) >= 0) * 1024 * 1024",
              "format": "table",
              "instant": true,
              "intervalFactor": 1,
              "refId": "D"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "POD GPU Usage",
          "transform": "table",
          "type": "table"
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fill": 0,
          "gridPos": {
            "h": 9,
            "w": 24,
            "x": 0,
            "y": 9
          },
          "id": 2,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "null",
          "paceLength": 10,
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "avg by (exported_namespace, exported_pod) (DCGM_FI_DEV_FB_USED{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"}) * 1024 * 1024",
              "format": "time_series",
              "intervalFactor": 1,
              "legendFormat": "{{exported_pod}}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "GPU Memory Usage (Average by Pod)",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "decbytes",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": false
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fill": 0,
          "gridPos": {
            "h": 10,
            "w": 24,
            "x": 0,
            "y": 18
          },
          "id": 5,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "null",
          "paceLength": 10,
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "avg by (exported_pod, exported_namespace) (DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\", exported_pod=~\"(.+)\"} / 100 >= 0)",
              "format": "time_series",
              "intervalFactor": 1,
              "legendFormat": "{{exported_pod}}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "GPU Utilization (Average by Pod)",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": false
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        }
      ],
      "refresh": false,
      "schemaVersion": 18,
      "style": "dark",
      "tags": [
        "AI Workload"
      ],
      "templating": {
        "list": [
          {
            "allValue": null,
            "current": {
              "text": "ntl-us-ibm-com",
              "value": "ntl-us-ibm-com"
            },
            "datasource": "Prometheus",
            "definition": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},  namespace)",
            "hide": 0,
            "includeAll": false,
            "label": "Namespace",
            "multi": false,
            "name": "namespace",
            "options": [],
            "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},  namespace)",
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "tagValuesQuery": "",
            "tags": [],
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          }
        ]
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ],
        "time_options": [
          "5m",
          "15m",
          "1h",
          "6h",
          "12h",
          "24h",
          "2d",
          "7d",
          "30d"
        ]
      },
      "timezone": "",
      "title": "Pod NVIDIA GPU Stats",
      "uid": "2sY55l0Ik",
      "version": 40
    }
kind: ConfigMap
metadata:
  labels:
    console.openshift.io/dashboard: "true"
  # This doesn't work on the developer dashboard. The reason is that the metrics collector is
  # in the gpu-operator namespace.  The developer view only can access metrics collected for the
  # current namespace, which would have to be gpu-operator.  We'd have to give authority to view
  # monitoring for all namespaces, which isn't that much greater than just allowing access to the
  # the admin view of observe.
  # console.openshift.io/odc-dashboard: "true"
  name: grafana-pod-nvidia-gpu-stats
  namespace: openshift-config-managed
